%dw 2.0
output application/java
---
if(vars.filterCondition != null)
	"SELECT COUNT(*) FROM (select ORDERSKU.*,ITEM.UOM from ORDERSKU,ORDERHEADER,ITEM where ORDERSKU.ITEM = ITEM.ITEM AND ORDERSKU.ORDERID = ORDERHEADER.ORDERID" ++ " AND " ++ vars.filterCondition ++ ")"
else	
	"SELECT COUNT(*) FROM (select ORDERSKU.*,ITEM.UOM from ORDERSKU,ORDERHEADER,ITEM where ORDERSKU.ITEM = ITEM.ITEM AND ORDERSKU.ORDERID = ORDERHEADER.ORDERID)"
