%dw 2.0
output application/java
---
if(vars.filterCondition != null)
	"SELECT COUNT(*) FROM (SELECT PROJORDERTOTAL.* FROM PROJORDERTOTAL,PROJORDERSUMMARY WHERE PROJORDERTOTAL.ORDERID = PROJORDERSUMMARY.ORDERID" ++ " AND " ++ vars.filterCondition ++ ")"
else
	"SELECT COUNT(*) FROM (SELECT PROJORDERTOTAL.* FROM PROJORDERTOTAL,PROJORDERSUMMARY WHERE PROJORDERTOTAL.ORDERID = PROJORDERSUMMARY.ORDERID)"