%dw 2.0
output application/json
---
using (
    sql = "SELECT ITEM.ITEM,ITEM.DESCR,ITEM.UOM,ITEM.DEFAULTUOM,ITEM.PRIORITY,ITEM.ITEMCLASS,ITEM.STORAGEGROUP,ITEM.PERISHABLESW,ITEM.VOL,ITEM.WGT,ITEM.DISCRETESW,UOMCATEGORYCONVFACTOR.SOURCEUOM,UOMCATEGORYCONVFACTOR.TARGETUOM,UOMCATEGORYCONVFACTOR.RATIO FROM ITEM LEFT JOIN UOMCATEGORYCONVFACTOR ON UOMCATEGORYCONVFACTOR.ITEM = ITEM.ITEM"
)
if (vars.filterCondition != null)
   sql ++ " WHERE " ++ vars.filterCondition
  else 
  	sql